base: 'https://mysearch.ddev.site'
languages:
  -
    title: Default
    enabled: true
    base: /
    typo3Language: de
    locale: de_DE.utf8
    iso-639-1: de
    websiteTitle: ''
    navigationTitle: Default
    hreflang: de_DE
    direction: ltr
    flag: de
    languageId: 0
  -
    title: English
    enabled: true
    base: /en/
    typo3Language: default
    locale: en_GB.utf8
    iso-639-1: en
    websiteTitle: ''
    navigationTitle: English
    hreflang: en-GB
    direction: ltr
    fallbackType: fallback
    fallbacks: '0'
    flag: gb
    languageId: 1
  -
    title: Deutsch
    enabled: true
    base: /de/
    typo3Language: de
    locale: de_DE.utf8
    iso-639-1: de
    websiteTitle: ''
    navigationTitle: Default
    hreflang: de_DE
    direction: ltr
    flag: de
    languageId: 2
rootPageId: 1
websiteTitle: 'Mysearch - dein Such-Index für deine Browser-Historie'
