<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "mysearch"
 *
 * Auto generated by Extension Builder 2020-08-27
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'MySearch',
    'description' => 'Plattform to build an index with elasticsearch based an own list of bookmarked links',
    'category' => 'plugin',
    'author' => 'Dr. Dieter Porth',
    'author_email' => 'info@mobger.de',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '10.1.0',
    'constraints' => [
        'depends' => [
            'typo3' => '10.4.6-10.4.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
