#
# Table structure for table 'tx_mysearch_domain_model_myindex'
#
CREATE TABLE tx_mysearch_domain_model_myindex (

	name varchar(255) DEFAULT '' NOT NULL COMMENT 'name of the index describing its function as  one word',
	vendor varchar(255) DEFAULT '' NOT NULL COMMENT 'vendor of the author of the index',
	index_ident varchar(255) DEFAULT '' NOT NULL COMMENT 'vendor+name = indexIdent ',
	index_score_factor decimal(11,2) DEFAULT 1.00 COMMENT 'from the user added factor for the index',
	title_trans_key text DEFAULT '' NOT NULL COMMENT 'translationkey for the title of the indes',
	description_trans_key text COMMENT 'translationkey for the  description of the index (optinal for internal use) ',
	linkbase_files_folder text COMMENT 'older of import-files with links for the index - helpfully predefined for scheduler',
	default_type varchar(255) DEFAULT '' NOT NULL COMMENT 'defined type of bookmarks - helpfully predefined for scheduler',
	default_grade varchar(255) DEFAULT '' NOT NULL COMMENT 'defined grade of the links in general - helpfully predefined for scheduler',
	login_param text COMMENT 'reserved for flex fields for login-infos currently unused',
	htaccess_param text COMMENT 'reserved for flex fields for htaccess-login-nfos, currently unused ',
	payment_param text COMMENT 'reserved for flex fields for paymentprocesses, currently unused'

);

#
# Table structure for table 'tx_mysearch_domain_model_linkbase'
#
CREATE TABLE tx_mysearch_domain_model_linkbase (

	link text COMMENT 'Webpage or absolute filepath to index in searchengine - one link for one index',
	link_hash varchar(255) DEFAULT '' NOT NULL COMMENT '',
	link_score_factor decimal(11,2) DEFAULT '1.00' NOT NULL COMMENT 'individuall score for link - defaultvalue is 1.00',
	index_ident varchar(255) DEFAULT '' NOT NULL '' COMMENT 'unique identifier fur the bas-link for this index',
	index_score_factor decimal(11,2) DEFAULT '1.00' NOT NULL COMMENT 'individuall score for index - defaultvalue is 1.00',
	type varchar(255) DEFAULT '' NOT NULL COMMENT 'distinguish betweene differen type of data - source, thesis, overview, archive, news, chats, logs, ...',
	grade varchar(255) DEFAULT '' NOT NULL COMMENT 'distinguish betweene differen grade of quality - super, good, solid, sufficient, poor, faulty, bad, ..',
	title varchar(255) DEFAULT '' NOT NULL COMMENT 'title given by the expert',
	description text COMMENT 'description  given by the expert - should contain all relevant keywords',
	crawl_deep int(11) DEFAULT '0' NOT NULL COMMENT ' generated by crawl-action, reset by index-deletation',
	crawl_start_link text COMMENT ' generated by crawl-action, reset by index-deletation',
	crawl_connections int(11) DEFAULT '0' NOT NULL COMMENT 'updated by crawl-actions, reset by index-deletation',
	login_param text COMMENT 'reserved for flex fields for login-infos currently unused',
	htaccess_param text COMMENT 'reserved for flex fields for htaccess-login-nfos, currently unused ',
	payment_param text COMMENT 'reserved for flex fields for paymentprocesses, currently unused'

);

#
# Table structure for table 'tx_mysearch_domain_model_typeoflink'
#
CREATE TABLE tx_mysearch_domain_model_typeoflink (

	name varchar(255) DEFAULT '' NOT NULL COMMENT 'internal name of of the value-type',
	translationkey varchar(255) DEFAULT '' NOT NULL COMMENT 'translatioonkey to describe the value-type',
	ident varchar(255) DEFAULT '' NOT NULL COMMENT 'unique identifier',
	description text COMMENT 'description, perhaps with same examples - only for internal use'

);

#
# Table structure for table 'tx_mysearch_domain_model_gradeoflink'
#
CREATE TABLE tx_mysearch_domain_model_gradeoflink (

	name varchar(255) DEFAULT '' NOT NULL COMMENT 'internal name of of the value-type',
	translationkey varchar(255) DEFAULT '' NOT NULL COMMENT 'translatioonkey to describe the value-type',
	ident varchar(255) DEFAULT '' NOT NULL COMMENT 'unique identifier',
	description text COMMENT 'description, perhaps with same examples - only for internal use'

);

#
# Table structure for table 'tx_mysearch_domain_model_myindex'
#
CREATE TABLE tx_mysearch_domain_model_myindex (
	categories int(11) unsigned DEFAULT '0' NOT NULL
);

#
# Table structure for table 'tx_mysearch_domain_model_linkbase'
#
CREATE TABLE tx_mysearch_domain_model_linkbase (
	categories int(11) unsigned DEFAULT '0' NOT NULL
);
